from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field, HttpUrl

from pegasus.schema.core import (
    DiseaseStatus,
    Identifier,
    LongText,
    SexComposition,
    ShortText,
    Text,
)

# ----------------------------
# Sheet: Source
# ----------------------------
class Source(BaseModel):
    """
    Citation and provenance information for each evidence stream, including publications, databases, and biosample details.
    """

    source_tag: ShortText = Field(
        ...,
        description="Unique identifier for the source.",
        json_schema_extra={"header": "source_tag", "example": "source_gtex_aorta"},
    )
    
    provenance: Optional[Identifier] = Field(
        default=None,
        description=(
            "Provenance type indicating the origin of the data source. "
            "Use lab_internal for unpublished data generated by your lab. "
            "Use publication for published data not deposited in a repository. "
            "Use the official name of the resource (e.g., GTEx, ENCODE)."
        ),
        json_schema_extra={"header": "provenance", "example": "GTEx"},
    )

    file_name: Optional[ShortText] = Field(
        default=None,
        description="Exact filename of the source dataset.",
        json_schema_extra={"header": "file_name", "example": "GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz"},
    )

    version: Optional[ShortText] = Field(
        default=None,
        description="Version or release of the dataset.",
        json_schema_extra={"header": "version", "example": "v8"},
    )
    
    url: Optional[HttpUrl] = Field(
        default=None,
        description="Web link to the source file used in the analysis.",
        json_schema_extra={"header": "url", "example": "https://gtexportal.org/"},
    )

    accession_id: Optional[ShortText] = Field(
        default=None,
        description="Accession identifier if the source file comes from the repository.",
        json_schema_extra={"header": "accession_id", "example": "GSE123456"},
    )

    doi: Optional[Text] = Field(
        default=None,
        description="DOI for the publication containing the source file.",
        json_schema_extra={"header": "doi", "example": "10.1038/s41586-020-2493-4"},
    )

    note: Optional[LongText] = Field(
        ...,        
        description="Extra details to aid interpretation of the source.",
        json_schema_extra={"header": "note", "example": "The analysis includes only samples from individuals aged 20–29."}
    )

    sample_origin: Optional[Literal["primary-tissue", "cell-line", "organoid", "iPSC-derived"] | ShortText] = Field(
        default=None,
        description="Biological origin of the sample (e.g., primary-tissue, organoid, cell-line, iPSC-derived).",
        json_schema_extra={"header": "sample_origin", "example": "primary-tissue"},
    )

    tissue: Optional[ShortText] = Field(
        default=None,
        description="Primary tissue sampled (detailed anatomical location).",
        json_schema_extra={"header": "tissue", "example": "aorta"},
    )

    cell_type: Optional[ShortText] = Field(
        default=None,
        description="Specific cell type, if applicable.",
        json_schema_extra={"header": "cell_type", "example": "alpha cells"},
    )

    cell_line: Optional[ShortText] = Field(
        default=None,
        description='Cell line name if sample_origin is "cell-line".',
        json_schema_extra={"header": "cell_line", "example": "K562"},
    )

    disease: Optional[DiseaseStatus] = Field(
        default=None,
        description="Disease status of the donor or sample.",
        json_schema_extra={"header": "disease", "example": "healthy"},
    )

    life_stage: Optional[ShortText] = Field(
        default=None,
        description="Developmental stage of the biosample.",
        json_schema_extra={"header": "life_stage", "example": "adult"},
    )

    treatment: Optional[LongText] = Field(
        default=None,
        description="Treatments or perturbations applied prior to or during data generation.",
        json_schema_extra={"header": "treatment", "example": "anti-IgM treated"},
    )

    sex: Optional[SexComposition] = Field(
        default=None,
        description="Sex composition of samples.",
        json_schema_extra={"header": "sex", "example": "mixed"},
    )

    species: Optional[Identifier] = Field(
        default=None,
        description="Species of the sample.",
        json_schema_extra={"header": "species", "example": "human"},
    )

    description: Optional[LongText] = Field(
        default=None,
        description="Brief summary of sample characteristics and intended use.",
        json_schema_extra={
            "header": "description",
            "example": (
                "Bulk pancreas tissue samples from healthy postmortem adult human donors in GTEx v10. "
                "Used for eQTL discovery. Samples span male and female donors aged approximately 20–70 years. "
                "No treatment applied."
            ),
        },
    )
